services:
  - type: web
    name: gusarov_stajirovka_bot
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        value: 7739788468:AAGKfIJD3V-Nl7kafJ6YlBmqp6Qkh8r90R0
