services:
  - type: web
    name: gusarov_stajirovka_bot
    env: docker
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 7739788468:AAGKfIJD3V-Nl7kafJ6YlBmqp6Qkh8r90R0
