services:
  - type: web
    name: telegram-course-bot
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: 7739788468:AAGKfIJD3V-Nl7kafJ6YlBmqp6Qkh8r90R0
        value: ваш_токен_бота
